//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class serverBUEntitiesConnection : DbContext
{
    public serverBUEntitiesConnection()
        : base("name=serverBUEntitiesConnection")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<TrainingPackage_Categories> TrainingPackage_Categories { get; set; }
    public virtual DbSet<TrainingPackage_MeetingTargets> TrainingPackage_MeetingTargets { get; set; }
    public virtual DbSet<TrainingPackage_Modules> TrainingPackage_Modules { get; set; }
    public virtual DbSet<TrainingPackage_Tasks> TrainingPackage_Tasks { get; set; }
    public virtual DbSet<TrainingPackage_TaskSubmissions> TrainingPackage_TaskSubmissions { get; set; }
    public virtual DbSet<TrainingPackage_User> TrainingPackage_User { get; set; }
    public virtual DbSet<TrainingPackage_UserRoles> TrainingPackage_UserRoles { get; set; }

    public virtual ObjectResult<TrainingPackage_ApprovalProcedure_Result> TrainingPackage_ApprovalProcedure(Nullable<int> userID)
    {
        var userIDParameter = userID.HasValue ?
            new ObjectParameter("userID", userID) :
            new ObjectParameter("userID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TrainingPackage_ApprovalProcedure_Result>("TrainingPackage_ApprovalProcedure", userIDParameter);
    }

    public virtual ObjectResult<TrainingPackage_ApprovalProcedure_Task_Result> TrainingPackage_ApprovalProcedure_Task(Nullable<int> userID, string taskName)
    {
        var userIDParameter = userID.HasValue ?
            new ObjectParameter("userID", userID) :
            new ObjectParameter("userID", typeof(int));

        var taskNameParameter = taskName != null ?
            new ObjectParameter("taskName", taskName) :
            new ObjectParameter("taskName", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TrainingPackage_ApprovalProcedure_Task_Result>("TrainingPackage_ApprovalProcedure_Task", userIDParameter, taskNameParameter);
    }

    public virtual ObjectResult<TrainingPackage_SignOffCaseNumber_Table_Result> TrainingPackage_SignOffCaseNumber_Table(Nullable<int> userID, string taskName)
    {
        var userIDParameter = userID.HasValue ?
            new ObjectParameter("userID", userID) :
            new ObjectParameter("userID", typeof(int));

        var taskNameParameter = taskName != null ?
            new ObjectParameter("taskName", taskName) :
            new ObjectParameter("taskName", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TrainingPackage_SignOffCaseNumber_Table_Result>("TrainingPackage_SignOffCaseNumber_Table", userIDParameter, taskNameParameter);
    }

    public virtual ObjectResult<TrainingPackage_SignOffDefault_Table_Result> TrainingPackage_SignOffDefault_Table(Nullable<int> userID, string taskName)
    {
        var userIDParameter = userID.HasValue ?
            new ObjectParameter("userID", userID) :
            new ObjectParameter("userID", typeof(int));

        var taskNameParameter = taskName != null ?
            new ObjectParameter("taskName", taskName) :
            new ObjectParameter("taskName", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TrainingPackage_SignOffDefault_Table_Result>("TrainingPackage_SignOffDefault_Table", userIDParameter, taskNameParameter);
    }

    public virtual ObjectResult<TrainingPackage_SignOffOne_Table_Result> TrainingPackage_SignOffOne_Table(Nullable<int> userID, string taskName)
    {
        var userIDParameter = userID.HasValue ?
            new ObjectParameter("userID", userID) :
            new ObjectParameter("userID", typeof(int));

        var taskNameParameter = taskName != null ?
            new ObjectParameter("taskName", taskName) :
            new ObjectParameter("taskName", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TrainingPackage_SignOffOne_Table_Result>("TrainingPackage_SignOffOne_Table", userIDParameter, taskNameParameter);
    }
}
