//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TrainingPackage_Categories
{
    public int ID { get; set; }
    public string Category { get; set; }
}

public partial class TrainingPackage_MeetingTargets
{
    public int ID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string Target { get; set; }
    public string Date { get; set; }
    public string TargetDesc { get; set; }
    public string CreatedBy { get; set; }
    public string Completion { get; set; }
}

public partial class TrainingPackage_Modules
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrainingPackage_Modules()
    {
        this.TrainingPackage_Tasks = new HashSet<TrainingPackage_Tasks>();
    }

    public int ID { get; set; }
    public string MODULE { get; set; }
    public Nullable<int> CATEGORY_ID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TrainingPackage_Tasks> TrainingPackage_Tasks { get; set; }
}

public partial class TrainingPackage_Tasks
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrainingPackage_Tasks()
    {
        this.TrainingPackage_TaskSubmissions = new HashSet<TrainingPackage_TaskSubmissions>();
    }

    public int ID { get; set; }
    public int MODULE_ID { get; set; }
    public string TASK_DESC { get; set; }

    public virtual TrainingPackage_Modules TrainingPackage_Modules { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TrainingPackage_TaskSubmissions> TrainingPackage_TaskSubmissions { get; set; }
}

public partial class TrainingPackage_TaskSubmissions
{
    public int ID { get; set; }
    public int USER_ID { get; set; }
    public int TASK_ID { get; set; }
    public string DEMO_BY { get; set; }
    public string DEMO_ON { get; set; }
    public string DATE { get; set; }
    public string COMPLETION { get; set; }
    public string APPROVED_BY { get; set; }

    public virtual TrainingPackage_Tasks TrainingPackage_Tasks { get; set; }
    public virtual TrainingPackage_User TrainingPackage_User { get; set; }
}

public partial class TrainingPackage_User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrainingPackage_User()
    {
        this.TrainingPackage_TaskSubmissions = new HashSet<TrainingPackage_TaskSubmissions>();
    }

    public int ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string PasswordResetCode { get; set; }
    public string Authorisation { get; set; }
    public Nullable<int> UserRoleID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TrainingPackage_TaskSubmissions> TrainingPackage_TaskSubmissions { get; set; }
    public virtual TrainingPackage_UserRoles TrainingPackage_UserRoles { get; set; }
}

public partial class TrainingPackage_UserRoles
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrainingPackage_UserRoles()
    {
        this.TrainingPackage_User = new HashSet<TrainingPackage_User>();
    }

    public int ID { get; set; }
    public string RoleName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TrainingPackage_User> TrainingPackage_User { get; set; }
}

public partial class TrainingPackage_ApprovalProcedure_Result
{
    public string ModuleName { get; set; }
    public string Task { get; set; }
    public string DemoBy { get; set; }
    public string demoOn { get; set; }
    public string date { get; set; }
    public string completion { get; set; }
    public string approval { get; set; }
}

public partial class TrainingPackage_ApprovalProcedure_Task_Result
{
    public string Task { get; set; }
    public string DemoBy { get; set; }
    public string demoOn { get; set; }
    public string date { get; set; }
    public string completion { get; set; }
    public string approval { get; set; }
}

public partial class TrainingPackage_SignOffCaseNumber_Table_Result
{
    public string taskDesc { get; set; }
    public string demoOn { get; set; }
    public string date { get; set; }
    public string completion { get; set; }
    public string approval { get; set; }
}

public partial class TrainingPackage_SignOffDefault_Table_Result
{
    public string taskDesc { get; set; }
    public string date { get; set; }
    public string completion { get; set; }
    public string approval { get; set; }
}

public partial class TrainingPackage_SignOffOne_Table_Result
{
    public string taskDesc { get; set; }
    public string demoBy { get; set; }
    public string date { get; set; }
    public string completion { get; set; }
    public string approval { get; set; }
}
