//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Case
{
    public int ID { get; set; }
    public Nullable<int> Case_Number { get; set; }
    public string Completion_Date { get; set; }
    public string Approval_Date { get; set; }
    public string Approval_Incident { get; set; }
    public string Approved_By { get; set; }
    public Nullable<int> Task_ID { get; set; }
    public Nullable<int> User_ID { get; set; }

    public virtual Task Task { get; set; }
    public virtual User User { get; set; }
}

public partial class Role
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Role()
    {
        this.Users = new HashSet<User>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<bool> Read_Permission { get; set; }
    public Nullable<bool> Submit_Task_Permission { get; set; }
    public Nullable<bool> Approve_Case_Permission { get; set; }
    public Nullable<bool> Add_Page_Permission { get; set; }
    public Nullable<bool> Delete_Page_Permission { get; set; }
    public Nullable<bool> Approve_Task_Permission { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class Task
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Task()
    {
        this.Cases = new HashSet<Case>();
    }

    public int ID { get; set; }
    public int UID { get; set; }
    public string Task_Name { get; set; }
    public string Description { get; set; }
    public int Module_Type_ID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Case> Cases { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.Cases = new HashSet<Case>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public int Role_ID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Case> Cases { get; set; }
    public virtual Role Role { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}
